project:
  type: website
  output-dir: docs

website:
  #title: ""
  site-url: https://jennaguffogg.com
  repo-url: https://github.com/ylaya/ylaya.github.io
  page-navigation: true
  navbar:
    type: light
    background: "#2c3e50"
    search: false
    pinned: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      # - text: "Projects"
      #   file: blog.qmd
      - text: "Publications & Media"
        file: publications.qmd
      - text: Awards
        file: awards.qmd

format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
    css: styles.css
    toc: false



